name: 'Full Trivy Scan with CycloneDX SBOM'
description: 'Perform a complete Trivy security scan, generate and merge CycloneDX SBOMs, and upload as artifact'
author: 'RomainValmo'

branding:
  icon: 'shield'
  color: 'blue'

# Licensed under the MIT License
# Copyright (c) 2025 RomainValmo

inputs:
  scan_github_actions:
    description: 'Scan GitHub Actions workflows and include used actions in the SBOM'
    required: false
    default: 'false'

outputs:
  sbom-file:
    description: 'Path to the merged SBOM file'
    value: sbom/merged-sbom.cdx.json

runs:
  using: 'composite'
  steps:
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release curl
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy
      shell: bash

    - name: Download Trivy DB
      run: trivy image --download-db-only
      shell: bash

    - name: Run trivy_scan.py
      run: python ${{ github.action_path }}/src/trivy_scan.py --scan-github-actions ${{ inputs.scan_github_actions }}
      shell: bash

    - name: Run merge_sbom.py
      run: python ${{ github.action_path }}/src/merge_sbom.py
      shell: bash

    - name: generate metadata file
      run: python ${{ github.action_path }}/src/metadata.py
      shell: bash

    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v4
      with:
        name: merged-sbom
        path: |
          sbom/merged-sbom.cdx.json
          sbom/metadata.json

    - name: Clean up
      run: rm -rf sbom/
      shell: bash