#!/bin/bash
# Commandes de test rapides - Cheat Sheet

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║          COMMANDES DE TEST - CHEAT SHEET                      ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📦 INSTALLATION"
echo "  make install                    # Installer dépendances"
echo "  pip install -r requirements-dev.txt"
echo ""
echo "🧪 TESTS"
echo "  make test                       # Tous les tests"
echo "  make test-unit                  # Tests unitaires uniquement"
echo "  make test-integration           # Tests d'intégration uniquement"
echo "  pytest test/ -v                 # Tests verbeux"
echo "  pytest test/test_trivy_scan.py  # Tests spécifiques"
echo ""
echo "📊 COUVERTURE"
echo "  make test-cov                   # Tests + couverture HTML"
echo "  pytest --cov=. --cov-report=term # Couverture dans le terminal"
echo "  open htmlcov/index.html         # Ouvrir le rapport HTML"
echo ""
echo "🔍 LINT & SYNTAXE"
echo "  make lint                       # Vérifier tout"
echo "  python -m py_compile *.py       # Vérifier syntaxe Python"
echo "  python -c \"import yaml; yaml.safe_load(open('action.yml'))\""
echo ""
echo "🧹 NETTOYAGE"
echo "  make clean                      # Nettoyer fichiers temp"
echo ""
echo "🎯 TESTS SPÉCIFIQUES"
echo "  pytest test/ -k \"test_extract\"  # Tests avec 'extract' dans le nom"
echo "  pytest test/ -m unit            # Tests avec marker 'unit'"
echo "  pytest test/ -x                 # Arrêter au premier échec"
echo "  pytest test/ --lf               # Re-run derniers échecs"
echo ""
echo "📈 CI/CD"
echo "  # Les tests s'exécutent automatiquement sur push/PR"
echo "  # Voir: .github/workflows/test.yml"
echo ""
echo "💡 ASTUCE"
echo "  # Vérification rapide avant commit:"
echo "  make lint && make test"
echo ""
